# PYTHON PROGRAMMING FUNDAMENTALS - PART B


This Notebook will cover the following topics:    
- Numpy basics
- Built-in methods and functions 
- Obtain shape, length and type of Numpy arrays
- Reshape 
- Minimum and maximum and their indices
- Mathematical Operations
- Indexing and slicing 
- Selection 



# NUMPY BASICS
- NumPy is a Linear Algebra Library used for multidimensional arrays
- Installation: Use the command window, type: conda install numpy

In [3]:
import numpy as np 

In [4]:
# One-dimensional array 
my_list = [5, 3, 10]
my_list

[5, 3, 10]

In [5]:
y = np.array(my_list)

In [6]:
y

array([ 5,  3, 10])

In [7]:
type(y)

numpy.ndarray

In [8]:
# multi-dimensional (Matrix definition) 
matrix = np.array([[1, 2], [3, 4]])

In [9]:
matrix

array([[1, 2],
       [3, 4]])

# BUILT-IN METHODS AND FUNCTIONS

In [10]:
# "rand()" uniform distribution between 0 and 1
x = np.random.rand(10)
x

array([0.77154612, 0.33487689, 0.30744666, 0.26916638, 0.23386907,
       0.93408703, 0.5240768 , 0.99756672, 0.53171099, 0.8484295 ])

In [11]:
x = np.random.rand(10, 10)
x

array([[0.22261423, 0.07494581, 0.70481954, 0.64411794, 0.98348916,
        0.27512918, 0.30676585, 0.38429863, 0.92951302, 0.22334213],
       [0.71900455, 0.73172559, 0.72210153, 0.22001801, 0.45115213,
        0.18034975, 0.86842368, 0.11696351, 0.53138711, 0.60634983],
       [0.46471142, 0.47383471, 0.80040504, 0.68485309, 0.08722778,
        0.07409461, 0.24980872, 0.04845491, 0.50108491, 0.48787947],
       [0.91616825, 0.25960812, 0.73151911, 0.45369375, 0.58820976,
        0.90285844, 0.89363026, 0.09337623, 0.96228839, 0.30930679],
       [0.15309013, 0.9720791 , 0.78280507, 0.48851644, 0.22492632,
        0.38963228, 0.88434139, 0.32824016, 0.84265121, 0.40796137],
       [0.31643162, 0.68732463, 0.94773745, 0.36702851, 0.01019731,
        0.55752016, 0.49801176, 0.83521216, 0.85232702, 0.14407828],
       [0.4170624 , 0.80789142, 0.28551561, 0.20028512, 0.62426602,
        0.41254247, 0.68416185, 0.86962895, 0.52054007, 0.93877051],
       [0.74452196, 0.47801408, 0.3885899

In [12]:
# "randn()" normal distribution between 0 and 1
x = np.random.randn(10)
x

array([ 1.09709618, -1.29340644, -1.80653064, -0.38959827, -0.37424597,
        1.19617959, -0.07955749,  1.58023548, -0.96578497,  1.06550309])

In [13]:
# "randint" is used to generate random integers between upper and lower bounds
x = np.random.randint(1, 10)
x

9

In [14]:
# "randint" is used to generate random integers between upper and lower bounds
x = np.random.randint(1, 100, 15)
x

array([50, 69, 58, 76, 57, 65, 79, 52, 69, 70, 98, 48, 60, 68, 72])

In [15]:
x = np.arange(1, 50)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [16]:
x = np.arange(1, 50, 5)
x

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46])

In [17]:
x = np.eye(5)
x

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [18]:
# Array of ones
x = np.ones(15)
x

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [19]:
# Matrices of ones
x = np.ones((15, 15))
x

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.

In [20]:
x.shape

(15, 15)

In [21]:
x = np.zeros(50)
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

# SHAPE, LENGTH AND TYPE OF NUMPY ARRAYS

In [22]:
# get Length 
len(y)

3

In [23]:
# get shape
y.shape

(3,)

In [24]:
matrix.shape

(2, 2)

In [25]:
matrix.dtype

dtype('int64')

# RESHAPE

In [32]:
y = np.array([3, 5, 7, 8, 9, 10, 11, 12, 13])
y.reshape(3,3)

array([[ 3,  5,  7],
       [ 8,  9, 10],
       [11, 12, 13]])

# MAX AND MIN VALUES AND THEIR INDEX

In [33]:
y.max()

13

In [34]:
y.min()

3

In [35]:
# Obtain the index of the max value
y.argmax()

8

In [36]:
# Obtain the index of the min value
y.argmin()

0

# MATHEMATICAL OPERATIONS

In [37]:
x = np.arange(1, 5)
x

array([1, 2, 3, 4])

In [38]:
y = np.arange(1, 5)
z = x+y
z

array([2, 4, 6, 8])

In [39]:
z = x**2
z

array([ 1,  4,  9, 16])

In [40]:
k = np.sqrt(z)
k

array([1., 2., 3., 4.])

In [41]:
z = np.exp(y)
z

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

# ELEMENTS SLICING AND INDEXING

In [42]:
x = np.random.randint(1,10, 10)
x

array([3, 8, 5, 2, 7, 3, 1, 9, 9, 1])

In [43]:
x[3]

2

In [44]:
x[0:3]

array([3, 8, 5])

In [45]:
# Broadcasting, altering several values in a numpy array at once
x[0:6] = 10
x

array([10, 10, 10, 10, 10, 10,  1,  9,  9,  1])

In [46]:
matrix = np.random.randint(1,10, (5, 5))
matrix

array([[1, 2, 4, 4, 4],
       [2, 5, 6, 1, 2],
       [1, 8, 1, 7, 1],
       [7, 3, 1, 5, 9],
       [2, 6, 3, 7, 7]])

In [47]:
# Get a row from a mtrix
matrix[2]

array([1, 8, 1, 7, 1])

In [48]:
# Get element
matrix[0][2]

4

In [49]:
mini_matrix = matrix[:3]
mini_matrix

array([[1, 2, 4, 4, 4],
       [2, 5, 6, 1, 2],
       [1, 8, 1, 7, 1]])

In [50]:
mini_matrix = matrix[2:]
mini_matrix

array([[1, 8, 1, 7, 1],
       [7, 3, 1, 5, 9],
       [2, 6, 3, 7, 7]])

In [51]:
mini_matrix = matrix[:, :2]
mini_matrix

array([[1, 2],
       [2, 5],
       [1, 8],
       [7, 3],
       [2, 6]])

In [52]:
mini_matrix = matrix[:, 2:]
mini_matrix

array([[4, 4, 4],
       [6, 1, 2],
       [1, 7, 1],
       [1, 5, 9],
       [3, 7, 7]])

# ELEMENTS SELECTION

In [59]:
matrix = np.random.randint(1,10, (5, 5))
matrix

array([[5, 4, 1, 1, 2],
       [5, 8, 5, 5, 4],
       [6, 9, 8, 1, 8],
       [6, 2, 8, 3, 2],
       [5, 6, 3, 5, 9]])

In [60]:
new_matrix = matrix[matrix>3]
new_matrix

array([5, 4, 5, 8, 5, 5, 4, 6, 9, 8, 8, 6, 8, 5, 6, 5, 9])

In [61]:
new_matrix = matrix[matrix%2==0]
new_matrix

array([4, 2, 8, 4, 6, 8, 8, 6, 2, 8, 2, 6])

# NOW YOU HAVE MASTERED NUMPY, GIVE YOURSELF A PAT ON THE SHOULDER!